# Generated by Django 4.1.5 on 2023-01-28 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='signed_amount',
            field=models.IntegerField(),
        ),
    ]
