# Generated by Django 4.1.5 on 2023-01-25 14:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('signature_date', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('sector', models.CharField(max_length=100)),
                ('signed_amount', models.CharField(max_length=100)),
            ],
        ),
    ]
